---

- name: Run Container Serverspec to check the VM Template
  ansible.builtin.shell:
    cmd: >
      ./start.sh
  environment:
    OS: "{{ serverspec_command.split(' ')[0] }}"
    VERSION: "{{ serverspec_command.split(' ')[1] }}"
    TARGET: "{{ vm_deploy_ip }}"
    LINUXROOT_USER_ENABLED: "{{ linuxroot_user_enabled | default(false) }}"
    PACKAGE: "{{ ubuntu_list_package | join(' ') }}"
  args:
    chdir: ../serverspec/
  delegate_to: localhost
  register: _serverspec_result
  ignore_errors: true

- name: Print result of Serverspec
  ansible.builtin.debug:
    var: _serverspec_result.stdout

- name: Check if Serverspec test has failures
  set_fact:
    serverspec_failed: >-
      {{ (_serverspec_result.stdout | regex_findall('Failed examples', multiline=True) | length) > 0 }}

- name: Print result of Serverspec test
  debug:
    msg: >-
      Serverspec {{ 'FAILED' if serverspec_failed else 'PASSED' }}

- name: Fail if Serverspec test failed (but continue)
  ansible.builtin.fail:
    msg: "Serverspec checked and found an example of the error. Exiting playbook."
  when: serverspec_failed
  ignore_errors: true
