---

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Verify host connectivity
      ansible.builtin.ping:
      ignore_unreachable: true
      register: _connectivity_test

    - name: Check Decom
      include_role:
        name: vm_decom
